"""add cascade delete to necessary relations

Revision ID: 8644bf1ecb08
Revises: b4512e2c7c55
Create Date: 2024-12-21 14:40:10.702098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8644bf1ecb08"
down_revision: Union[str, None] = "b4512e2c7c55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("accounts_owner_id_fkey", "accounts", type_="foreignkey")
    op.create_foreign_key(
        None, "accounts", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("transactions_owner_id_fkey", "transactions", type_="foreignkey")
    op.create_foreign_key(
        None, "transactions", "accounts", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.create_foreign_key(
        "transactions_owner_id_fkey", "transactions", "accounts", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.create_foreign_key(
        "accounts_owner_id_fkey", "accounts", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
