"""add security_code_verified field to users table

Revision ID: 8dbc521004e8
Revises: 57c528b7ece8
Create Date: 2024-12-17 15:56:11.963347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dbc521004e8"
down_revision: Union[str, None] = "57c528b7ece8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "security_code_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "security_code_verified")
    # ### end Alembic commands ###
