"""add user_id column to transactions table

Revision ID: 90c6288ea8d4
Revises: 7e171eba4463
Create Date: 2025-01-26 16:04:19.141184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90c6288ea8d4"
down_revision: Union[str, None] = "7e171eba4463"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "transactions", "sender_recipient", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_foreign_key(
        None, "transactions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.alter_column(
        "transactions", "sender_recipient", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("transactions", "user_id")
    # ### end Alembic commands ###
