"""edit logo_path name and default value to store only a filename of the profile picture

Revision ID: a6387226399c
Revises: 37f277560330
Create Date: 2024-11-14 19:31:07.845886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6387226399c'
down_revision: Union[str, None] = '37f277560330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(), server_default='default.png', nullable=False))
    op.drop_column('users', 'logo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logo_path', sa.VARCHAR(), server_default=sa.text("'/logos/default.png'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
