"""add cvv and expiration date fields to account info

Revision ID: b4512e2c7c55
Revises: b3ef94d9cbdc
Create Date: 2024-11-20 17:37:59.080327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4512e2c7c55'
down_revision: Union[str, None] = 'b3ef94d9cbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('card_verification_value', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('expiration_date', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['primary_account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'expiration_date')
    op.drop_column('accounts', 'card_verification_value')
    # ### end Alembic commands ###
